config/google-cloud-storage/config.json, config/local/config.json, config/s3-compliant/config.json, readme.md, src/assignment/parse-assignment.spec.ts, src/assignment/parse-assignment.ts, src/config/config.ts, src/config/interfaces.ts, src/config/schema/assignment-schema-validator.ts, src/config/schema/documents-schema-validator.ts, src/config/schema/validator.spec.ts, src/config/schema/validator.ts, src/datasaur/interfaces.ts, src/handlers/create-project.handler.ts, src/handlers/create-projects.handler.ts, src/utils/interface.ts, src/utils/object-storage/helper.ts, src/utils/states/script-state.spec.ts, src/utils/states/script-state.ts, src/utils/states/team-projects-state.spec.ts, src/utils/states/team-projects-state.ts, src/utils/states/test-helper.ts, tsconfig.json
=> Improve Config interfaces

readme.md, src/datasaur/query.ts, src/handlers/create-projects.handler.ts, src/handlers/export-projects.handler.ts, src/utils/publish/helper.ts, src/utils/publish/publishProjectFiles.ts, src/utils/publish/publishZipFile.ts, src/utils/questionset.ts, src/utils/states/getStates.ts, src/utils/states/script-state.ts
also: add notes on assignment strategy
=> Patch: additional logging and state info update on exports

.gitignore, package-lock.json, package.json, readme.md, sample/storage/azure-blob-storage/config.json, src/assignment/parse-assignment.ts, src/config/interfaces.ts, src/config/schema/credential-schema-validator.ts, src/config/schema/export-schema-validator.ts, src/config/schema/validator.ts, src/documents/get-documents.ts, src/handlers/create-projects.handler.ts, src/utils/object-storage/azure-blob-storage.ts, src/utils/object-storage/helper.ts, src/utils/object-storage/index.ts, src/utils/publish/constants.ts, src/utils/publish/publishProjectFiles.ts, src/utils/publish/publishZipFile.ts, src/utils/states/script-state.ts
To test this out, use the sample `config.json` file in `sample/storage/azure-blob-storage`. Change the fields there to the appropriate values. 
To prepare for the project and pcw script:
1. Get the connection string from Azure Storage Account
2. Create a container in Azure Blob Storage
3. Upload the pcw script to the container (preferably into a folder), and the project also to the container (also into a folder).
4. Setup the config file by changing the values
5. Run robosaur
6. Robosaur saves the project state in Blob Storage, in a `state` folder (will be created if it doesn't exist)
7. Robosaur can also export the project results to Blob Storage, into a `download` folder (will be created if it doesn't exist) in the specified container
Any feedback is appreciated, thanks!
=> Added Azure Blob Storage Support

graphql.schema.json, quickstart/doc-based/config/config.json, quickstart/row-based/config/config.json, quickstart/token-based/config/config.json, readme.md, robosaur.md, sample/pcwPayload/config.json, sample/storage/azure-blob-storage/config.json, sample/storage/google-cloud-storage/config.json, sample/storage/local/config.json, sample/storage/remote-files/config.json, sample/storage/s3/config.json, src/config/interfaces.ts, src/config/schema/export-schema-validator.ts, src/datasaur/export-project.ts, src/generated/graphql.ts, src/handlers/export-projects.handler.ts
1. replaced customScriptId to fileTransformerId
2. adjusted documentation and descriptions to support the change
=> #11914 Replace all customScriptId to fileTransformerId

src/handlers/create-projects.handler.ts, src/transformer/pcw-transformer/setConfigFromPcw.ts
- We should also support cloud object storage, not just local filesystem
=> #12286 Fix assignment with PCW to support multiple sources

readme.md, src/datasaur/get-project.ts, src/datasaur/get-team-tags.ts, src/handlers/apply-tags.handler.ts, src/index.ts
The term refers to REST API method behavior
- `PUT`: replace all tags except the global
- `PATCH`: add new one
=> #12277 Add method option for apply tags

src/handlers/export-projects.handler.ts
**Root cause** 
- in stateful export, list-of-projects from GQL are checked vs local / state list-of-project. 
- there was a logic error,
- our query to GQL filters by tag ✅  
- we update our projects in statefile ✅ 
- when obtaining valid projects, we missed checking against list-of-projects from GQL response
**Changes** 
- added an if-check to ensure project is in the graphql response (using project.name as project.id can be undefined on creation failure)
- update logging, now should list out all filter used, not just the project status
=> Fix stateful export by tags

src/handlers/export-projects.handler.ts, src/handlers/revert-completed-projects.handler.ts, src/utils/states/script-state.ts, src/utils/states/team-projects-state.ts
- Remove `export` state after revert command so that those projects can be exported again
=> #12495 Stateful revert command

src/datasaur/query.ts
- Access token from OAuth2 is only valid for one hour. So, if a command is running longer than that, it will throw unauthorized error.
- Add try catch to retry generating access token once if the error is indeed unauthorized
=> #12947 Fix long running command due to expired access token

src/config/interfaces.ts, src/datasaur/create-project.ts, src/transformer/pcw-transformer/setConfigFromPcw.ts
1. Added config for custom api text extractor ID for project creation input
=> #13988 [Robosaur] Support custom OCR API when creating a project

src/transformer/pcw-transformer/setConfigFromPcw.ts
Fixed default value set to empty string
it should be set to undefined instead
=> fixed default custom api value

src/datasaur/create-project.ts, src/documents/get-local-documents.ts, src/handlers/create-projects.handler.ts, src/transformer/pcw-transformer/setConfigFromPcw.ts
- should allow mixed labeling project for image & audio pair to be created with the questions attached
sample payload: 
```json
{
"datasaur": {
"host": "http://localhost:8080",
"clientId": "CLIENT_ID",
"clientSecret": "CLIENT_SECRET"
},
"projectState": {
"source": "local",
"path": "projectState.json"
},
"create": {
"kinds": [
"TOKEN_BASED",
"DOCUMENT_BASED"
],
"teamId": "TEAM_ID",
"files": {
"source": "local",
"path": "FOLDER_PATH"
},
"pcwPayloadSource": {
"source": "inline"
},
"pcwAssignmentStrategy": "AUTO",
"pcwPayload": {
"type": "ASR",
"projectSettings": {
"autoMarkDocumentAsComplete": false,
"enableEditLabelSet": false,
"enableEditSentence": true,
"hideLabelerNamesDuringReview": false,
"hideLabelsFromInactiveLabelSetDuringReview": false,
"hideOriginalSentencesDuringReview": false, …
```
=> Improve mixed labeling project creation

sample/SI/config_si.json, sample/rex/config_rex.json
1. Added config for project creation with custom OCR API and ML assisted labeling
=> #14111 [Robosaur] Rex project creation configuration

.dockerignore, .gitignore, docker-compose.yml, entrypoint.sh, readme.md, restart-robosaur.sh, robosaur.Dockerfile
1. Dockerized robosaur
2. Added container for mongodb
3. Entrypoint is only dummy script -> calls for a project creation and then loops infinitely
=> #14110 dockerize robosaur

src/handlers/export-projects.handler.ts, src/handlers/export/helper.ts
1. Split export functions to smaller reusable functions
2. Moved utilities for export into helper file
Tested both stateful and stateless export, works as expected
=> Cleanup Export Project Handler

src/execution/handler-context.ts, src/execution/helpers.ts, src/logger/logger-service.ts
- Add popResolver method to clear the resolver
- Add preventNewTraceIdGeneration to enable nested context call
=> fix logger trancing error

graphql.schema.json, src/config/interfaces.ts, src/datasaur/auto-label.ts, src/generated/graphql.ts, src/handlers/auto-label.handler.ts
1. Added role to auto label query parameter
2. Added role to auto label config
=> Added role to auto label query

.env.example, on-premise/scheme/default/robosaur.env, src/database/entities/teamPayloads/teamX.entity.ts, src/datasaur/rex/abort-job.ts, src/datasaur/rex/orchestrate-job.ts, src/export/save-to-database.ts, src/export/send-request.ts
- update end_ocr only after saving results to database done
- end_ocr will be null when there is error occurred
- add RETRY_DELAY to configure sleep between retry when calling the channel
=> #14752 bug fixes

src/database/repository.ts, src/datasaur/rex/check-record-status.ts
Fixed SI Robosaur to cancel job when OCR Status is `Stopped`
=> Si fix cancel

graphql.schema.json, src/config/schema/export-schema-validator.ts, src/generated/graphql.ts, src/transformer/pcw-transformer/helper/document-settings.mapper.spec.ts, src/transformer/pcw-transformer/interfaces.ts
=> #14582 Update GraphQL schema regarding deleted unused `LabelSetResolver` GraphQL

on-premise/scheme/default/robosaur.env, on-premise/scheme/default/template.txt
1. Change memory limit from 2000M to 500M for producer and consumer container on template.txt
2. Add filling guide for GRAFANA_DOMAIN environment variable on robosaur.env
=> #15468 template update

src/datasaur/rex/cancel-state.ts
1. Add prefix id before {id} value
2. Add prefix page before {page} value
on stoppped document log message.
=> #15807 - Improve message readability

src/datasaur/rex/handle-project-creation-input-files.ts, src/export/save-to-database.ts
Problems
- robosaur prints wrong message
Changes
- add catch and rethrow
=> Fix Invalid doc recognition cancel message

sample/rex/config_rex.json, src/handlers/auto-label.handler.ts
1. Update labelsets value on docker-config/config.json to meet with changes made on ocrosaurus and post-processing module.
2. Remove checkRecordStatus on auto-label.handler.ts for TEXT_EXTRACTION stage to prevent error due to no page information available.
=> implement new labelsets and remove a checkRecordStatus to prevent error

sample/rex/config_rex.json
add role: REVIEWER for robosaur docker-config/config.json autoLabel key
=> /#15813 role reviewer

src/datasaur/rex/handle-project-creation-input-files.ts
add checkRecordStatus function inside for loop which call document-recognition API.
=> #16085 cancel in progress document recognition

on-premise/scheme/default/loki/promtail-config.yaml
- Added a filter to promtail to read project names starting with `datasaur-`
=> added datasaur-* as projects that will be read by grafana

on-premise/scheme/default/down.sh, on-premise/scheme/default/restart.sh, on-premise/scheme/default/run.sh, on-premise/scheme/default/stop.sh
- Upgraded scripts to use Compose V2
=> #14180 changed to docker compose v2

.github/workflows/artifact-builder.yaml, build.sh, on-premise/.gitignore, on-premise/scheme/default/docker-compose.yml, on-premise/scheme/default/down.sh, on-premise/scheme/default/restart.sh, on-premise/scheme/default/robosaur.env, on-premise/scheme/default/run.sh, on-premise/scheme/default/stop.sh
- Add volume to loki Docker container to persist logs.
- Add volume to grafana Docker container to persist configurations.
- Use docker compose rather than docker-compose.
- Create Artifact Builder Github action.
A. Build Robosaur
- Pre-build
1. Go to target virtual machine
2. Get the non-root user ID that you will use to deploy the application
```
id -u
```
3. Get the non-root group ID that you will use to deploy the application
```
id -g
```
- Using Github Action
1. Go to Github Action
2. Select Artifact Builder workflow
3. Press Run workflow
4. Input this values
- robosaur image version (required, default is main)
- User ID for build (optional, default is 0). Replace this with the targeted virtual machine user ID
- Group ID for build (optional, default is 0). Replace this with the …
=> #17777 Dockerize Retraining service
